baseURL = "https://seleniumhq.github.io/docs/site"
languageCode = "en-US"
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

canonifyurls = "true"

title = "Documentation for Selenium"
theme = "hugo-theme-learn"
copyright = "2013-{year}"

# Code highlighting
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "solarized-dark"

enableGitInfo = true

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "selenium"
  editURL = "https://github.com/SeleniumHQ/docs/edit/gh-pages/docs_source_files/content/"
  ghrepo = "https://github.com/SeleniumHQ/docs/"
  description = "Documentation for Selenium"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Selenium"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/SeleniumHQ/docs"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Report a bug"
url = "https://github.com/seleniumhq/docs/issues"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> How to contribute"
url = "contributing"
weight = 30

[Languages.es]
title = "Documentación de Selenium"
weight = 2
languageName = "Español"

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo en GitHub"
identifier = "ds"
url = "https://github.com/SeleniumHQ/docs"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Reportar un problema"
url = "https://github.com/seleniumhq/docs/issues"
weight = 11

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Créditos"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Cómo contribuír"
url = "contributing"
weight = 30

[Languages.nl]
title = "Selenium documentatie"
weight = 3
languageName = "Nederlands"

[[Languages.nl.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/SeleniumHQ/docs"
weight = 10

[[Languages.nl.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Meld een probleem"
url = "https://github.com/seleniumhq/docs/issues"
weight = 11

[[Languages.nl.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.nl.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Hoe bij te dragen"
url = "contributing"
weight = 30

[Languages.zh-cn]
title = "Selenium 文档"
weight = 4
languageName = "中文简体"

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/SeleniumHQ/docs"
weight = 10

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-exclamation-triangle'></i> Report a bug"
url = "https://github.com/seleniumhq/docs/issues"
weight = 11

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "front_matter/copyright_and_attributions"
weight = 20

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> How to contribute"
url = "contributing"
weight = 30
